// Site dossier: the evidence an agent needs to build a standalone client,
// written as plain files under sites/<name>/dossier/. Spoor lays it out; it
// does not decide what the site "is".

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { CookieInfo, StorageSnapshot } from "../shared/types.ts";
import { authChain, endpoints, lifetimes, type AuthChain, type CookieLifetime, type Endpoint, type JwtInfo } from "./inspect.ts";
import { paths } from "./paths.ts";
import { readFlows, readRecordingFile, type RecordingRef } from "./store.ts";
import { writeJson } from "./store.ts";

export function authMarkdown(chain: AuthChain): string {
  const lines = [
    "## Auth chain",
    "",
    `Hosts in order: ${chain.hosts.join(" → ") || "(none)"}`,
    "",
    `Protocol hints: ${chain.protocol_hints.join(", ") || "none seen"}`,
    "",
    "| seq | method | status | host | path | sets cookies | sends cookies | params |",
    "|---|---|---|---|---|---|---|---|",
  ];
  for (const s of chain.steps) {
    const params = Object.entries(s.params).map(([k, v]) => `${k}=${v}`).join("<br>");
    const path = s.location ? `${s.path}<br>→ ${s.location.slice(0, 120)}` : s.path;
    lines.push(`| ${s.sequence} | ${s.method} | ${s.status ?? "-"} | ${s.host} | ${esc(path)} | ${s.sets_cookies.join(", ")} | ${s.sends_cookies.join(", ")} | ${esc(params)} |`);
  }
  return lines.join("\n") + "\n";
}

export function lifetimesMarkdown(l: { cookies: CookieLifetime[]; jwts: JwtInfo[] }): string {
  const lines = [
    "## Cookies at the end of the recording",
    "",
    "| domain | name | expires | remaining | flags | set by seq |",
    "|---|---|---|---|---|---|",
  ];
  for (const c of l.cookies) {
    const flags = [c.httpOnly && "HttpOnly", c.secure && "Secure", c.sameSite !== "no_restriction" && `SameSite=${c.sameSite}`].filter(Boolean).join(" ");
    lines.push(`| ${c.domain} | ${c.name} | ${c.session ? "session" : c.expires} | ${c.remaining_s !== undefined ? duration(c.remaining_s) : "-"} | ${flags} | ${c.set_by.join(", ")} |`);
  }
  lines.push("", "## Tokens (JWT) seen", "");
  if (l.jwts.length === 0) lines.push("None.");
  for (const j of l.jwts) {
    lines.push(`- **${j.where}**: expires ${j.expires ?? "?"}${j.lifetime_s ? `, lifetime ${duration(j.lifetime_s)}` : ""}`);
    lines.push(`  \`${JSON.stringify(j.claims)}\``);
    if (j.seen_in.length > 1) lines.push(`  also in: ${j.seen_in.slice(1).join("; ")}`);
  }
  return lines.join("\n") + "\n";
}

export function endpointsMarkdown(eps: Endpoint[]): string {
  const lines = ["## Endpoints", "", "| method | origin | path | n | status | response | query | request body | example seq |", "|---|---|---|---|---|---|---|---|---|"];
  for (const e of eps) {
    lines.push(`| ${e.method} | ${e.origin} | ${esc(e.path)} | ${e.count} | ${e.statuses.join(", ")} | ${e.content_types.join(", ")} | ${e.query_params.join(", ")} | ${e.request_body ?? ""} | ${e.examples.join(", ")} |`);
  }
  return lines.join("\n") + "\n";
}

function esc(s: string): string {
  return s.replace(/\|/g, "\\|");
}

export function duration(s: number): string {
  const neg = s < 0;
  s = Math.abs(s);
  const out = s >= 86400 ? `${(s / 86400).toFixed(1)} d` : s >= 3600 ? `${(s / 3600).toFixed(1)} h` : s >= 60 ? `${Math.round(s / 60)} min` : `${s} s`;
  return neg ? `expired ${out} ago` : out;
}

/** Write dossier/{auth,lifetimes,endpoints}.md and dossier.json from one recording. */
export function buildDossier(site: string, rec: RecordingRef): string[] {
  const flows = readFlows(rec);
  const cookies = readRecordingFile<CookieInfo[]>(rec, "cookies.json", []);
  const storage = readRecordingFile<StorageSnapshot[]>(rec, "storage.json", []);
  const chain = authChain(flows);
  const life = lifetimes(flows, cookies, storage, rec.meta.stopped ? Date.parse(rec.meta.stopped) : Date.now());
  const eps = endpoints(flows);
  const dir = paths.dossier(site);
  mkdirSync(dir, { recursive: true });
  const header = `<!-- generated by spoor dossier from recording ${rec.id} (${rec.meta.started}); edit notes.md, not this file -->\n# ${site}\n\n`;
  writeFileSync(join(dir, "auth.md"), header + authMarkdown(chain));
  writeFileSync(join(dir, "lifetimes.md"), header + lifetimesMarkdown(life));
  writeFileSync(join(dir, "endpoints.md"), header + endpointsMarkdown(eps));
  writeJson(join(dir, "dossier.json"), { site, recording: rec.id, auth: chain, lifetimes: life, endpoints: eps });
  return readdirSync(dir).map(f => join(dir, f));
}

export function readDossierFile(site: string, name: string): string {
  return readFileSync(join(paths.dossier(site), name), "utf8");
}
